
{
    'name': 'HR Safco',
    'version': '19.0.1.0.0',
    'category': 'Human Resources',
    'summary': 'Saudi-specific HR, attendance, contract and payroll customizations',
    'description': "Adding saudi market required extra fields in employee profile and payroll flows.",
    'author': 'Aymen RAHMANI',
    'maintainer': 'Aymen RAHMANI',
    'license': 'AGPL-3',
    'depends': ['base', 'hr', 'hr_payroll', 'mail', 'hr_leave', 'hr_contract', 'hr_attendance'],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/cron.xml',
        'data/hr_contract_sequence.xml',
        'views/hr_attendance_view.xml',
        'views/hr_contract_view.xml',
        'views/hr_payslip_run.xml',
        'views/view_resource_calendar.xml',
        'views/hr_employee_view.xml',
        'wizard/normalize_attendences_views.xml',
    ],
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': False,
}
