# -*- coding: utf-8 -*-
{
    'name': 'MRP Safco',
    'version': '19.0.1.0.0',
    'category': 'Manufacturing',
    'summary': 'Custom SAFCO manufacturing reports and fields',
    'description': 'Custom SAFCO MRP fields, views and PDF reports.',
    'author': 'Aymen RAHMANI',
    'license': 'LGPL-3',
    'depends': ['base', 'sale', 'mrp', 'mrp_account_enterprise'],
    'data': [
        'views/views_model.xml',
        'views/z_mrp_report.xml',
        'views/z_mrp_header.xml',
        'views/z_mrp_production_order_report.xml',
        'views/z_mrp_process_batch_card_report.xml',
        'views/z_mrp_bom_request_report.xml',
        'views/z_mrp_product_analysis_report.xml',
        'views/z_mrp_product_release_certificate_report.xml',
        'views/z_mrp_tree_report.xml',
        'views/report.xml',
    ],
    'demo': [],
    'installable': True,
    'application': False,
    'auto_install': False,
}
